# docker-compose.linux.yml
# Use este arquivo no servidor Linux para o SNMP funcionar corretamente
# Comando: docker compose -f docker-compose.linux.yml up -d

services:
  monitor-toner:
    build: .
    container_name: monitor-toner
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - TZ=America/Sao_Paulo
    network_mode: host   # necessário para SNMP UDP alcançar as impressoras
